import logging
LOGGING_MODE = logging.WARNING
LOG_FILE_PATH = "/tmp/check_nas.log"
#LOG_FILE_PATH = "C:/temp/check_nas.log"
RAID_PATHS = ["/dev/md0",]
HDD_PATHS = ["/dev/nvme0n1", "/dev/sda", "/dev/sdb", "/dev/sdc"]
DF_PATHS = ["/", "/usr", "/tmp", "/var", "/boot/efi", "/data", "/mnt/raid4to"]
DF_THREATHOLD = 80 # Statut KO si > 80%
DF_HISTORY_PATH = "/data/history"
#DF_HISTORY_PATH = "C:/LAME/Perso/history"
DF_HISTORY_FILE_FORMAT = "df_*.log"
DF_HISTORY_OUTPUT = "/tmp/df_chart.png"
#DF_HISTORY_OUTPUT = "C:/temp/df_chart.png"
MAIL_SMTP = "smtp.free.fr"
MAIL_PORT = 587  # Port pour TLS
MAIL_USER = "merlet.l@free.fr"
MAIL_PASSWORD = "u6V!5XVxTjYFjx"
MAIL_DEFAULT_RECIPIENT = "lautux76@gmail.com"
NAS_PHOTOS_PATH = "/mnt/raid4to/Photos/"
PCLOUD_PHOTOS_PATH = "/NAS/Photos/"
NAS_DATA_PATH = "/mnt/raid4to/Data/"
PCLOUD_DATA_PATH = "/NAS/Data/"
NAS_TEST_PATH = "/mnt/raid4to/test/"
PCLOUD_TEST_PATH = "/NAS/test/"
NAS2PCLOUD_LOG_DIR = "/home/laurent/Documents/rclone/"
RCLONE_OPTIONS = ["--verbose", "--progress"] #--dry-run
ICON_GOOD = "icons/Gnome-emblem-default.svg"
ICON_BAD = "icons/Gnome-dialog-warning.svg"
